### ISSUE TITLE
XY Grid offsets in grid-margin-x don't include margin 

### ISSUE THREAD

**Issue by steelwolf** [zurb/foundation-sites#10697]
#### How to reproduce this bug: 
1. Set up two grids using grid-margin-x.
2. Give the top grid a div with `small-1 cell` followed by a div with `auto cell`
3. Give the bottom grid a div with `small-offset-1 auto cell`
4. Bottom is slightly misaligned relative to the top

#### Test case link: https://codepen.io/anon/pen/wrppqM

From what I can tell in my testing, the issue occurs in _position.scss:
`.grid-margin-x > .small-offset-1 {`
`margin-left: calc(8.33333% + 0.625rem);`
`}`

Should be:
`.grid-margin-x > .small-offset-1 {`
`margin-left: calc(8.33333% + 0.9375rem);`
`}`

**Comment by rafibomb** [comment]
Looks like it's using the gutter for the small breakpoint? A PR would really help here, are you able to submit one?

**Comment by brettsmason** [comment]
This is the ongoing responsive gutters problem (@kball 😢)

Basically it needs to generate breakpoint sized versions of each offset (your demo works correctly on small) but needs to swap the gutter size on medium like the example @rafibomb posted (but should be in a media query). The same issue was fixed for other xy grid components so shouldn't be too hard to replicate for this.

**Comment by steelwolf** [comment]
I'm working on it, but am not yet familiar enough with the individual components to fix this at a low level. In my current implementation I've "fixed" the small breakpoint by overriding with what I posted above. :/

**Comment by DanielRuf** [comment]
Still relevant. See https://codepen.io/DanielRuf/pen/xxKqrVW

**Comment by VladimirPittner** [comment]
This is still an issue.
My guess, if I am not mistaken, is that it is caused by the fact, that when there is `.grid-margin-x` it have this CSS:
```
.grid-margin-x {
  margin-left: -0.625rem;
  margin-right: -0.625rem;
}
```
Which will then affect this `margin-left: calc(8.33333% + 0.625rem);` 
I guess 8.3% of parent which have 0 margin is not the same as 8.3% of parent which have negative margin, because the `width` from which the % is calculated is different.

The sad part of this is that I don't have any nice solution for this problem. Seems like the combination of margin gutters and offset will not work.
