### ISSUE TITLE
[F6][Drilldown] Height consumption calc not working

### ISSUE THREAD

**Issue by aibrean** [zurb/foundation-sites#7070]
When there are very long nested submenu (`menu vertical submenu is-drilldown-submenu is-drilldown-sub`) in the drilldown, the bottom gets cropped off.

Seems like the `_getMaxDims` from JS isn't working right or height needs to be adjusted elsewhere (it's set to 100% on `.is-drilldown-sub`) to account for long titles that may wrap multiple lines.

(stubbed due to sensitive information)
![image](https://cloud.githubusercontent.com/assets/6740252/11307356/a2aba1d2-8f85-11e5-9db8-301df11bd9be.png)

**Comment by gakimball** [comment]
Hey @aibrean, sorry for not getting to this sooner! I'm working on recreating your issue, but I'm not able to. I made [this test case](https://github.com/zurb/foundation-sites/blob/develop/test/visual/drilldown/long-drilldown-menu.html), a simple drilldown with a ton of items within a sub-menu. The drilldown expands fine, no matter how many items are added.

It's possible the issue has been fixed in a newer version of Foundation, but just in case, I need your help recreating it. If you want to fiddle with the example I linked, you can clone the foundation-sites repo, set it up, and then run `npm run test:visual`. Then you can look at this page yourself and mess around with it.

Thanks for your help! :)

**Comment by aibrean** [comment]
The issue is not the amount of items, but the _length_ of the items (i.e. item title).

**Comment by gakimball** [comment]
Thanks for the clarification—I was able to recreate the issue. I got most of the way there but I've run into an issue with `.getBoundingClientRect()`, so we'll need to do a bit more testing. Here's the pull request for the fix: #8320

**Comment by andycochran** [comment]
@aibrean Can you still reproduce this issue with the latest version? If so could you please make a [codepen](http://codepen.io/rafibomb/pen/xVVGOB) and reopen this issue?
