### ISSUE TITLE
[Foundation 6 for Sites] Panini, partials breaks watch on save

### ISSUE THREAD

**Issue by firmmedia** [zurb/foundation-sites#7075]
**How can we reproduce this bug?**

1. run foundation watch (all is working good no bugs or errors)
2. create a partial in ./src/partials/ (I made header.html) 
note: in my test I removed the first row of code from the index.html file and added it into the partial (header.html) so 
This is the content I used in header.html:
``<div class="row">
  <div class="large-12 columns">
    <h1>Welcome to Foundation for Sites</h1>
    <span>  yes it is...</span>
  </div>
</div> ``
3. save header.html 
4. include the handlebars partial in the default.html like s:
    {{> header}}
    {{> body}}
5. save the default.html

** I expected the page to be compiled/ flattened with handle bars via panini and then reload the browser with browser sync**

**Instead gulp show this message:
``[11:06:19] Starting 'pages:reset'...
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[11:06:19] Starting 'pages'...
[11:06:19] Finished 'pages' after 3.88 ms
[BS] Reloading Browsers...``

the issue:
The page is not rebuilt and the browser does not reload...
if I exit foundation watch with ctl-c and reload foundation watch the files compile and the browser sync serves the flattened html file from the src files.
**
Once the files are added I have tried restarting foundation watch and each time the partial is saved I am meet with the same issue.

I have looked around the forum and have not seen any reports of this issue.  I have tested this pattern on 3 machines following the instructions in the foundation 6 documentation and get the same results.

Please update me if there are any fixes or threads on this issue.  I would really love to use this feature of foundation cli for fast markup (thank you.)

ps.  Everything works great if no partials are created.

**Comment by firmmedia** [comment]
This is the first issue I am reporting so please let me know if I can provide any additional information to make debugging this easier.

Thanks again ahead of time for any help on this one.

**Comment by frankspin89** [comment]
Same issue i have: https://github.com/zurb/foundation-sites/issues/7057

**Comment by gakimball** [comment]
Alright, there are two issues here:

- `gulp.watch()` not seeing new files. That's an easy fix.
- When a layout or partial changes, BrowserSync reloads the page before Panini is done processing the changes. If you reload the page a second time, you'll see the changes.

So the `pages:reset` task needs to act less asynchronous.

**Comment by gakimball** [comment]
Just pushed [this commit](https://github.com/zurb/foundation-zurb-template/commit/98c304b11a4861f2dfad3e82288c933d2317a0db) to the ZURB Template which should resolve both issues. Once Gulp 4 is out there will be a more elegant solution to these race conditions, which happen because, in general, everything Gulp does is asynchronous.

In my own testing, the race conditions are gone, but it's possible that they'll still crop up, I'm not sure.

**Comment by firmmedia** [comment]
After reading the comments on #7057 I ran through this process again and you are correct if you reload the page the changes will show.  However browser sync no longer is triggered when any file changes are made once a partial has been saved.  gakimball Thank you for helping to solve this.  It is appreciated.

**Comment by firmmedia** [comment]
I just pulled the changes.  The issue is resolved.  When saving partials and pages the code is flattened and the browser sync functions properly.

Good Work!

I noticed one additional thing and this is not a bit deal: 

If I create a new page or partial I still need to reload the browser after saving the file to bet everything back on path.

This is not a big deal just wondering if you experienced the same thing on your end.

**Comment by gakimball** [comment]
@firmmedia Yes, that's the race condition I was describing. I think there's a more airtight way to avoid it, but it will make the Gulpfile more verbose, which is a little annoying. *But* BrowserSync should behave the same way no matter what file you're saving, so it's probably worth the effort.

**Comment by firmmedia** [comment]
@gakimball  so is it safe to say that this issue is resolved until gulp 4 is released and a more elegant approach can be taken?  Or are you still going to try to make this happen?  Sorry.  I am a new user to gulp so this is a bit over my head.  I do not want to waste your time if this issue isn't effecting others because I do not know how to fix it myself. I am happy to call this bug squashed if it would be best to address the race condition when gulp updates.  

Your fix works great.  I do not mind reloading the page when a new page or partial is added that is not a big deal.  I am just happy that I can use handlebars to template pages now.

**Comment by gakimball** [comment]
@firmmedia It'll definitely affect other people, which is why it's probably worth fixing. I'll close this for now, but I'll ping you when I get a more robust fix in. I probably won't get to it today, since we're prepping another patch for Foundation.

Thanks for reporting the issue! :)

**Comment by firmmedia** [comment]
Just noticed that when more partials are called in the default.html file in my case
``{{> header}}
  {{> body}}
  {{> footer}}''

it seems that the issue worsens and files need to be saved several times.  to make the change show.  

Thank you for getting it to a workable place for me and for keeping me up to date when the more robust fix is added.  

I will mess with it on my end and if I can figure anything out I will let you know.

Thanks again.

**Comment by thehanseiway** [comment]
Hi!
I still have this issue when installing template from foundation cli.
When it will be fixed or I should manually copy your commit that fixes this bug?
And also after using your commit I still have this error:
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
Should I change it to gulp.watch()?

**Comment by gakimball** [comment]
@thehanseiway The `gulp.run() has been deprecated` thing is just a warning, not an error.

If you just installed a new project with the CLI, you should have the commit referenced in your project. Can you tell me exactly what problem you had?

**Comment by thehanseiway** [comment]
Thank for such quick answer. Yes sorry warning.
I had the same problem as @firmmedia.
I solved it with this commit. I was just asking why it's not in installed project and can I change gulp.run() in gulp.watch()?
Thank you.

**Comment by gakimball** [comment]
@thehanseiway If you created the project *before* the commit went in (which was on Nov 20, so that doesn't seem likely), then you wouldn't have it. We can't auto-update the build systems of existing projects, because they aren't connected to this Git repo.

The solution isn't bulletproof however, and there may be instances where BroserSync reloads before Panini is done processing. In those instances, reloading the page again should resolve it.

We have an [update to the ZURB Template](https://github.com/zurb/foundation-zurb-template/tree/gulp4) in the works which upgrades to Gulp 4, which can more elegantly handle the issue outlined here. It's just about done, but we don't have a timeline to release it yet. It works very well, though, and could be used for new projects right now.
