### ISSUE TITLE
[F6][Top Bar] Top Bar sub menu items not clickable

### ISSUE THREAD

**Issue by dasmikko** [zurb/foundation-sites#7143]
When using the Complete Package, and the foundation.js version 6.0.1, the Top Bar sub menu items, are not clickable.

**Comment by bnbc** [comment]
Yes same problem here : http://www.presticar-automobiles.com/ on "ACCES VIP"

**Comment by zzplab** [comment]
Yes, I've seen that too: 6.0.0, 6.0.1, 6.0.3 all have the same issue.
I've still a testsite using the foundation 6.0.0-alpha.1 version for JS. Then the topbar/submenu works fine.
So seems like JS issue, not CSS.

**Comment by Tschef** [comment]
This seem to be a known issue and @zurbchris has created a branch called 'dd-menu' and a pull request from what i see that will hopefully fix this soon.

https://github.com/zurb/foundation-sites/pull/7162

**Comment by zurbchris** [comment]
Should be fixed as of 6.0.4, please reopen if not.

**Comment by mauricemoss** [comment]
Works fine on Desktop, but doesn't on Tablets. Submenu only disappears on item-click and nothing happens.

**Comment by devanflaherty** [comment]
I'm seeing this same issue, any updates on this?

**Comment by bnbc** [comment]
Fixed with new version !

**Comment by jcw-** [comment]
@bnbc Which version is this fixed in, 6.4?

**Comment by bnbc** [comment]
Few months ago so in 6.1 or 6.2.

**Comment by jcw-** [comment]
Hmmm, I'm running 6.3.0 and it is broken. Confirmed on both Android device and using mobile emulation in chrome dev tools.

**Comment by devanflaherty** [comment]
Still broken for me as well on iPad and any touch device.

If I long press the item I can open it when the iOS menu pops up and asks
me if I would like to.

**Comment by IllusionPerdu** [comment]
in the develop branch this was fixed... for fix this you can delete the  **touchend.zf.dropdownmenu** in this code /js/foundation.dropdownMenu.js

```javascript
        // Handle Leaf element Clicks
        if (_this.options.closeOnClickInside) {
          this.$menuItems.on('click.zf.dropdownmenu touchend.zf.dropdownmenu', function (e) {
            var $elem = $(this),
                hasSub = $elem.hasClass(parClass);
            if (!hasSub) {
              _this._hide();
            }
          });
        }
```
