### ISSUE TITLE
Reproducing the Foundation 5 responsive nav menu - problems

### ISSUE THREAD

**Issue by therealbenhogan** [zurb/foundation-sites#8076]
Hi,

I want to create the Foundation 5 responsive nav menu using the new navbar components - with drilldown for smaller screens. 

Here's an example http://codepen.io/therealbenhogan/pen/yexPWw

1. on a standard screen, the drop down menus don't align below the top level parent item  - I've added some CSS in the example above, to ensure they do but I'm not sure this is required
2. if you drag the viewport in to trigger the drill down menu, the sub page nav arrows aren't displaying at all.
3. again, for smaller screens, the height of the drill down container remains constant - I've put a heading in, below the navigation to illustrate this. In Foundation 5, the height of the drill down container varied depending upon the contents within it. You can see the effect if you click on the about us link.
4. again for smaller screens, using the drill down, in Foundation 5 you could navigate to the parent item as you click through the sub pages - it would appear as the first item in the next page .... whereas here, there is no way to visit the parent item page. Taking this example, you can't visit the about us page (or any other parents), you have to click through all the way to the final child. Perhaps I've missed something in the docs for this?

**Comment by brettsmason** [comment]
@therealbenhogan for point 4 I've actually put a PR together to enable this: [8060](https://github.com/zurb/foundation-sites/pull/8060)

I think 1 is a bug which hopefully should be fixed soon, and I expect 2 is aswell. Not sure on 3 if that's the desired behaviour or not.

**Comment by therealbenhogan** [comment]
Hi, 

Many thanks for getting back.

I'll look out for the fixes!

Re point 3, I think it should be desired, otherwise a site will have a gap below the navigation and before the content begins which will look bad, particuarly on a mobile. This did not happen in Foundation 5.

One other thing which I forgot to mention - and may be an easy fix - on F5 the width of the sub nav li's was not fixed like it is now, so you didn't get nav item labels moving down a line which happens now. Is this something that can be easily changed?

**Comment by zurbchris** [comment]
1 is fixed with 4d86718

2 is up to you, we don't fix a width for your list items, which will go full width by themselves. We do, however fix a max-width to the `is-drilldown` container that is wrapped around the menu so there's a target  for the translates. You can style `.is-drilldown` directly in your css to fix a width.

3 was a design choice when we were building this thing, we didn't like the content jumping around, which causes page reflows, among other things. Accordion Menu still expands the page.

4 has a pr open, as mentioned, that will probably get pulled in for 6.2

**Comment by therealbenhogan** [comment]
Thanks for getting back - I'll take another look at point 2. 

Is there an easy fix regarding 3, so we can make the drill down height change depending on its contents?

Many thanks!

**Comment by SalahAdDin** [comment]
I have some problems with this too.

**Comment by colin-marshall** [comment]
@therealbenhogan I'm closing this issue, feel free to reopen it if you are still having problems. Thanks!
